Remove CDN and added assets folder
avantifellows/portal-frontend pull request #20
Opened 2021-10-18 06:39 UTC by sudheshna-donthineni

2021-10-19 07:30 UTC, deepansh96 requested changes

2021-10-19 07:30 UTC, deepansh96 commented on src/assets/images/autorenew.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M12 6v3l4-4-4-4v3c-4.42 0-8 3.58-8 8 0 1.57.46 3.
rename this file to loading_spinner or something

2021-10-19 07:30 UTC, deepansh96 commented on src/assets/images/add_circle.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#C62828"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M13 7h-2v4H7v2h4v4h2v-4h4v-2h-4V7zm-1-5C6.48 2 2
This circle is coming out to be red? Is it on purpose?

2021-10-19 07:30 UTC, deepansh96 commented on src/assets/images/add_circle.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#C62828"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M13 7h-2v4H7v2h4v4h2v-4h4v-2h-4V7zm-1-5C6.48 2 2
<img width="486" alt="Screenshot 2021-10-19 at 11 37 52 AM" src="https://user-images.githubusercontent.com/20169829/137853211-0c863d1c-25c0-4458-bfe8-9b8501ac6dff.png">

2021-10-19 07:30 UTC, deepansh96 commented on src/assets/images/remove_circle.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#388E3C"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M7 11v2h10v-2H7zm5-9C6.48 2 2 6.48 2 12s4.48 10 1
And the remove circle icon is coming out to be green. Should be opposite right?

<img width="584" alt="Screenshot 2021-10-19 at 11 38 33 AM" src="https://user-images.githubusercontent.com/20169829/137853280-64f43919-22cb-4fc6-a386-01a401ac874d.png">

2021-10-19 07:30 UTC, deepansh96 commented on src/components/SRNEntry.vue
> +       <inline-svg class="text-4xl pr-1"
I see that you've changed `pr-2` to `pr-1` but that is just a workaround and this causes the icon to become super small.
Ideally what you want to do, is in the `.svg` file, remove all the `fill`, `height`, `width` tags. You don't want that hardcoded into your svg files. When you remove that, then you can control all those attributes here, where you're using the svg.

2021-10-19 07:30 UTC, deepansh96 commented on src/components/SRNEntry.vue
> +          :src="require('@/assets/images/remove_circle.svg')"></inline-svg>
(read this comment after reading the comment attached to add_circle.svg below) 
You'll have to do the same thing here, as discussed in the other comment, remove all the fill, height, width tags from the original svg file and then specify height and width here

2021-10-19 14:12 UTC, deepansh96 requested changes

2021-10-19 14:12 UTC, deepansh96 commented on src/assets/images/add_circle.svg
> +<svg xmlns="http://www.w3.org/2000/svg" ><path d="M0 0h24v24H0V0z" fill="none"/><path d="M13 7h-2v4H7v2h4v4h2v-4h4v-2h-4V7zm-1-5C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.4
Don't remove viewbox! It's necessary for the content inside an svg to be positioned properly. You can read about what a viewbox is.

2021-10-19 14:12 UTC, deepansh96 commented on src/assets/images/loading_spinner.svg
> +<svg xmlns="http://www.w3.org/2000/svg" ><path d="M0 0h24v24H0V0z" fill="none"/><path d="M12 6v3l4-4-4-4v3c-4.42 0-8 3.58-8 8 0 1.57.46 3.03 1.24 4.26L6.7 14.8c-.45-.83-.7-1.79-.7-2.8 0-3.31 2.69-6 6
You can remove `fill` altogether

2021-10-19 14:12 UTC, deepansh96 commented on src/assets/images/loading_spinner.svg
> +<svg xmlns="http://www.w3.org/2000/svg" ><path d="M0 0h24v24H0V0z" fill="none"/><path d="M12 6v3l4-4-4-4v3c-4.42 0-8 3.58-8 8 0 1.57.46 3.03 1.24 4.26L6.7 14.8c-.45-.83-.7-1.79-.7-2.8 0-3.31 2.69-6 6
also, don't remove viewbox

2021-10-19 14:12 UTC, deepansh96 commented on src/assets/images/remove_circle.svg
> +<svg xmlns="http://www.w3.org/2000/svg"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M7 11v2h10v-2H7zm5-9C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-
- don't remove viewbox
- remove fill

2021-10-19 14:14 UTC, deepansh96 commented on src/assets/images/remove_circle.svg
> +<svg xmlns="http://www.w3.org/2000/svg"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M7 11v2h10v-2H7zm5-9C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-
Also, increase the size of the loading spinner

2021-10-20 06:22 UTC, sudheshna-donthineni commented on src/assets/images/loading_spinner.svg
> +<svg xmlns="http://www.w3.org/2000/svg" ><path d="M0 0h24v24H0V0z" fill="none"/><path d="M12 6v3l4-4-4-4v3c-4.42 0-8 3.58-8 8 0 1.57.46 3.03 1.24 4.26L6.7 14.8c-.45-.83-.7-1.79-.7-2.8 0-3.31 2.69-6 6
The fill is the attribute for that specific path. For example, it's a hollow circle. if I remove the fill, it becomes a solid circle.

2021-10-20 06:47 UTC, deepansh96 commented
There's one bug (as shown below) and that is because you used the same viewBox in all SVGs. Look at the spinner. It's not spinning about it's center.

https://user-images.githubusercontent.com/20169829/138041928-5433991e-b433-44a7-98bb-1d1b2ebb369d.mov

You should use the viewBox value which was originally present in the svg

2021-10-21 10:30 UTC, deepansh96 requested changes

2021-10-21 10:30 UTC, deepansh96 commented on src/components/SRNEntry.vue
> +       <inline-svg class="fill-current text-green-600 pt-1 pl-1 h-10 w-10"
```suggestion
       <inline-svg class="fill-current text-green-600 h-10 w-10 pr-1"
```

2021-10-21 10:30 UTC, deepansh96 commented on src/components/SRNEntry.vue
> +      <inline-svg class="text-black text-4xl m-auto animate-spin h-10 w-10"
```suggestion
      <inline-svg class="text-black text-4xl m-auto animate-spin h-20 w-20"
```

2021-10-21 10:30 UTC, deepansh96 commented on src/components/SRNEntry.vue
> +          <inline-svg class="fill-current text-red-600 pt-2 pl-2 h-10 w-10"
```suggestion
          <inline-svg class="fill-current text-red-600 h-8 w-8"
```

2021-10-21 12:28 UTC, merged